### ISSUE TITLE
Cannot find Stata directory

### ISSUE THREAD

**Issue by tartifola** [kylebarron/stata-png-fix#2]
Hi,
thank you for providing the script. I'm trying to use it in a fresh new Linux Mint 19 environment. I have two issues:

1. line 22 of 'compile-stata-png-fix.sh' generates

       ./compile-stata-png-fix.sh: line 22: stata-png.patch: No such file or directory

It seems easy to fix;

2. after running the script Stata still does not work. Stata opens, there are no question marks nor icons anymore and I get a "Cannot find Stata directory"

![screenshot from 2018-07-16 14-21-16](https://user-images.githubusercontent.com/25226433/42758295-5d8fdf1c-8903-11e8-913d-8d62d56ddbd2.png)

 Then Stata crashes.

I double checked the path to the directory and to be sure I also tried without modifing your script consistently put the Stata directory in ~/local. I'm probably missing something stupid but I don't see it. Any help?

Thanks in advance

**Comment by tartifola** [comment]
Hi,
I forgot to specify that if I explicitly run

LD_LIBRARY_PATH=~/local/stata-png-fix/lib/ ./xstata-mp

it works perfectly.

**Comment by kylebarron** [comment]
Hmm. I'll have to try this myself inside a new VM. The issue might be that I permanently have `LD_LIBRARY_PATH` set to include `~/local/lib/`, so maybe I didn't realize others would need to manually set the path.

**Comment by kylebarron** [comment]
For line 22, 

https://github.com/kylebarron/stata-png-fix/blob/1e6cef256b2cd9f4cbf8187515bd52e94b617725/compile-stata-png-fix.sh#L22

I think I just need to change this to 
```
patch -p1 < ${cwd}/stata-png.patch 
```
Can you try that?

**Comment by tartifola** [comment]
> Hmm. I'll have to try this myself inside a new VM. The issue might be that I permanently have 
> LD_LIBRARY_PATH set to include ~/local/lib/, so maybe I didn't realize others would need to >manually set the path.
 
That's indeed my case. 

> I think I just need to change this to
>patch -p1 < ${cwd}/stata-png.patch 
>Can you try that?

Clearly it works flawlessly. Thanks again also for your prompt reply and let me know if you need me to do more testing in my environment.

**Comment by kylebarron** [comment]
Can you try again with the newest commits? You shouldn't have to manually set `LD_LIBRARY_PATH`; that's what this is for:

https://github.com/kylebarron/stata-png-fix/blob/a61139113eb3fd29bdaae9f8fdcb71c0117e810e/stata-png-fixed.sh#L14

But until the most recent commit, I had been replacing instead of adding to the path, and that might have caused the issue.

**Comment by tartifola** [comment]
Now everything works perfectly. I've tried also on a different machine with Linux Mint 19 and the default bash environment since I use the zsh with some personal config. 

Thanks for your work.

**Comment by kylebarron** [comment]
It works without having to manually set `LD_LIBRARY_PATH`?

**Comment by tartifola** [comment]
Yes. I've just followed your instructions, without setting anything else.
