### ISSUE TITLE
Clarification about use of sudo

### ISSUE THREAD

**Issue by larsvilhuber** [kylebarron/stata-png-fix#4]
Thanks for making this updated version of the script. I think it might be worthwhile to make the distinction *why* `sudo` is used: 

- I took a sysadmin approach, i.e., there are multiple users on the machine (other researchers, RAs) who also need to use the same Stata installation. In that case, installing it in a system-wide location is necessary, and fixing it for all users might suggest the use of `sudo` (you *could* do it differently, but somewhere along the way, you need `sudo)`
- Your approach is the RIGHT approach if you are on a single-user machine, i.e., you are the only user on the machine (e.g. laptop). In that case, `sudo` is overkill. 

The *real* solution remains for Stata to implement this right...

**Comment by kylebarron** [comment]
I agree. I added a note to this effect to the README.
